### PR TITLE
Adds support for Carthage by adding xcodeproj in the root directory.

### PR DESCRIPTION
**Pull request by wrutkowski-tyro**
Hello, thanks for creating this library! I'd like to use it with [Carthage](https://github.com/Carthage/Carthage) so I created a branch that supports Carthage. Basic requirement is to have a Xcodeproj in the root directory which I created using [xcodegen](https://github.com/yonaskolb/XcodeGen) and I checked in `project.yml` so it should be easy to recreate the Xcode project again if needed. I had to provide bundle identifier so I picked `com.github.oleghnidets`. Let me know if you are happy with this change.

### CODE REVIEW

**Comment by oleghnidets** [comment]
Hi @wrutkowski-tyro!
Thank you for great contribution.

Carthage is awesome improvement to this library. I definitely like to see it supported. I will check the changes in couple of days. 
Did you integrate the library from the branch? Is it working fine with Carthage?

**Comment by wrutkowski-tyro** [comment]
Yes, we integrated it to our project using carthage and (for now) using my fork as a reference. It's working as expected.

Cartfile:
```
github "wrutkowski-tyro/OHMySQL" "carthage-support"
```

carthage update:
```
❯ carthage update --platform iOS --use-xcframeworks OHMySQL
*** Fetching OHMySQL
*** Checking out OHMySQL at "acfb90f443c34b802e0d12f9df08898bf6f19eaa"
*** xcodebuild output can be found in /var/folders/rl/bncglbnj2pgbyjnbp54qsvbd2dfnjy/T/carthage-xcodebuild.ZXcbZI.log
*** Building scheme "OHMySQL" in OHMySQL.xcodeproj
```

The only manual step required to integrate except dropping xcframework of OHMySQL from `Carthage/Build` folder was to manually add `MySQL.xcframework` that's part of your repo. Carthage doesn't have a support for dependency that's part of the same repository to move the `MySQL.xcframework` to the Build folder.

**Comment by oleghnidets** [comment]
Hey @wrutkowski-tyro 
I like this PR, but I wish to have this improvement documented. 

Could you create a documentation (`*.md`) in `docs` folder? Describe there how to configure `xcodegen` to generate projects. 
I'm going to update documentation in near future, so I will have a reference to your documentation. 
Thanks

**Comment by wrutkowski-tyro** [comment]
Hi @oleghnidets 👋 I added documentation as requested.

**Review by alemesle — APPROVED** [review]

**Review by oleghnidets — APPROVED** [review]

**Comment by wrutkowski-tyro** [comment]
Thanks for merging @oleghnidets 👏 Would you be able to create a tag / release so we can start using master instead of the fork?

**Pull request merged**
